### ISSUE TITLE
Config of Parts doesn't seem to be migrated from Portlet params

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/cms2xp#32]
It looks like the portlets of old aren't analysed and migrated fully. The XSLT file can define `<xsl:param>` that will show settings (strings or content selectors) inside the admin interface of old CMS. Usually we did this in the old days to be able to use the same XSLT-file in multiple Portlets, just different config.

In modern XP this is normally one Part, with different config per instance (not a Fragment).

It looks like this is not migrated properly. Leading to problems using the content.

**Example exported data:**
This menuitem:
Sites / www.nav.no / Menu items / no / Person / Skjemaer-for-privatpersoner / Skjemaer / Arbeid, helse og sykdom / arbeidsavklaringspenger / Arbeidsavklaringspenger

One part there looks like it has been joined in with other parts just because it uses same XSLT-file, even if the config differs.

In XP it has a Page Config with Part "Skjema 3: Velg skjema (AAP)" and it uses the file "velg-skjema.xsl" in CMS, the same file 10 other portlets uses. It has 3 params in CMS, but no config at all in XP.

**Comment by hjelmevold** [comment]
If I remember correctly, xsl:params could be a simple text string value with optional type specified with attribute as="xs:string" or xs:integer or xs:boolean, but also where type was a content key specified with `<type>page</type>`, or `<type>content</type>`.

Each CMS portlet also has a Document with an HtmlArea, but hopefully none of our customers are still using this! It has been deprecated since version 4.4 I think.
The same goes for Border Stylesheet (which sort of is a Layout in XP) – I think Østfold Energi uses them, but other than that I can't remember anyone else who does.

**Comment by aro** [comment]
The portlet parameters were not being exported to the part config.
Fixed. It needs a re-run of cms2xp to get the data updated.
